server:
  port: 8761

spring:
  application:
    name: service-registry-dev

eureka:
  instance: # Eureka general configurations
    prefer-ip-address: true
  client: # Eureka client configurations
    register-with-eureka: false
    fetch-registry: false
  server: # Eureka server configurations
    wait-time-in-ms-when-sync-empty: 0
